export const SET_ACCENT_COLOR = "THEME-EDITOR/COMMANDS/SET_ACCENT_COLOR";
export const SET_MAIN_BACKGROUND_COLOR =
  "THEME-EDITOR/COMMANDS/SET_MAIN_BACKGROUND_COLOR";
export const SET_SECONDARY_BACKGROUND_COLOR =
  "THEME-EDITOR/COMMANDS/SET_SECONDARY_BACKGROUND_COLOR";
