export const AUTHENTICATE_USER = "SIGN-IN/COMMAND/AUTHENTICATE_USER";
export const TOKEN_RECEIVED = "SIGN-IN/EVENTS/TOKEN_RECEIVED";
export const TOKEN_REVOKED = "SIGN-IN/EVENTS/AUTHENTICATION_REVOKED";
export const AUTHENTICATION_FAILED = "SIGN-IN/EVENTS/AUTHENTICATION_FAILED";
